/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: LPC54608J512
package_id: LPC54608J512BD208
mcu_data: ksdk2_0
processor_version: 6.0.3
pin_labels:
- {pin_num: '109', pin_signal: PIO1_1/FC3_RXD_SDA_MOSI/CTIMER0_CAP3/SCT0_GPI5/USB1_OVERCURRENTN, label: 'J12[12]/U29[4]/SW5/P1_1-USER_PB-USB1_OVRCURn', identifier: SW5}
- {pin_num: '189', pin_signal: PIO0_5/CAN0_TD/FC4_RXD_SDA_MOSI/CTIMER3_MAT0/SCT0_GPI5/EMC_D(3)/ENET_MDIO, label: 'U28[C9]/RP3[1]/JS32[1]/SW3/P0_5-ISP1/P0_5-EMC_D3',
  identifier: SW3;EMC_D3}
- {pin_num: '185', pin_signal: PIO0_4/CAN0_RD/FC4_SCK/CTIMER3_CAP0/SCT0_GPI4/EMC_D(2)/ENET_MDC, label: 'U28[B8]/RP3[2]/JS32[3]/SW4/P0_4-ISP0/P0_4-EMC_D2', identifier: SW4;EMC_D2}
- {pin_num: '169', pin_signal: PIO3_3/LCD_VD(17)/FC9_TXD_SCL_MISO, label: 'J9[8]/LED2/P3_3-USR_LED2', identifier: LED2}
- {pin_num: '4', pin_signal: PIO2_2/ENET_CRS/FC3_SSEL3/SCT0_OUT6/CTIMER1_MAT1, label: 'J9[6]/LED3/P2_2-CT1MAT1-USR_LED3', identifier: LED3}
- {pin_num: '13', pin_signal: PIO3_14/SCT0_OUT4/FC9_RTS_SCL_SSEL1/CTIMER3_MAT1/TRACEDATA(2), label: 'J13[5]/LED1/P3_14-CT3MAT1-USR_LED1', identifier: LED1}
- {pin_num: '207', pin_signal: PIO0_1/CAN1_TD/FC3_CTS_SDA_SSEL0/CTIMER0_CAP0/SCT0_GPI1/PDM0_DATA, label: 'U26[14]/J14[1]/P0_1-ISP_FC3_SSEL0', identifier: ISP_FC3_SSEL0}
- {pin_num: '178', pin_signal: PIO0_3/FC3_RXD_SDA_MOSI/CTIMER0_MAT1/SCT0_OUT1/SCT0_GPI3/EMC_D(1), label: 'U28[B9]/RP3[3]/JS34[1]/U26[11]/J14[2]/P0_3-ISP_FC3_MOSI/P0_3-EMC_D1',
  identifier: ISP_FC3_MOSI;EMC_D1}
- {pin_num: '174', pin_signal: PIO0_2/FC3_TXD_SCL_MISO/CTIMER0_CAP1/SCT0_OUT0/SCT0_GPI2/EMC_D(0), label: 'U28[A8]/RP3[4]/JS35[1]/U24[11]/J14[3]/P0_2-ISP_FC3_MISO/P0_2-EMC_D0',
  identifier: ISP_FC3_MISO;EMC_D0}
- {pin_num: '196', pin_signal: PIO0_0/CAN1_RD/FC3_SCK/CTIMER0_MAT0/SCT0_GPI0/PDM0_CLK, label: 'U26[13]/J14[4]/P0_0-ISP_FC3_SCK', identifier: ISP_FC3_SCK}
- {pin_num: '75', pin_signal: PIO3_13/SCT0_OUT9/FC9_CTS_SDA_SSEL0/CTIMER3_CAP1/EMC_FBCK/TRACEDATA(1), label: 'J14[8]/P3_13-BRIDGE_GPIO', identifier: BRIDGE_GPIO}
- {pin_num: '16', pin_signal: PIO3_24/FC2_RTS_SCL_SSEL1/CTIMER4_CAP0/USB0_VBUS, label: 'J11[9]/J9[1]/U10[2]/J17[4]/U19[2]/P3_24-FC2_SCLX', identifier: FC2_SCLX}
- {pin_num: '8', pin_signal: PIO3_23/FC2_CTS_SDA_SSEL0/UTICK_CAP3, label: 'J11[10]/J9[3]/U10[3]/J17[5]/U19[10]/P3_23-FC2_SDAX', identifier: FC2_SDAX}
- {pin_num: '172', pin_signal: PIO3_4/LCD_VD(18)/FC8_CTS_SDA_SSEL0/CTIMER4_CAP1, label: 'J12[10]/U19[3]/P3_4-ACCL_INTR', identifier: ACCL_INTR}
- {pin_num: '71', pin_signal: PIO0_23/MCLK/CTIMER1_MAT2/CTIMER3_MAT3/SCT0_OUT4/SPIFI_CSN/ADC0_11, label: 'J13[8]/U27[1]/P0_23-SPIFI_CSn-MCLK', identifier: SPIFI_CSn}
- {pin_num: '110', pin_signal: PIO0_26/FC2_RXD_SDA_MOSI/CLKOUT/CTIMER3_CAP2/SCT0_OUT5/PDM0_CLK/SPIFI_CLK/USB0_IDVALUE, label: 'J13[2]/U27[6]/P0_26-SPIFI_CLK', identifier: SPIFI_CLK}
- {pin_num: '76', pin_signal: PIO0_24/FC0_RXD_SDA_MOSI/SD_D(0)/CTIMER2_CAP0/SCT0_GPI0/SPIFI_IO(0), label: 'J13[6]/U27[5]/P0_24-SPIFI_IO0', identifier: SPIFI_IO0}
- {pin_num: '87', pin_signal: PIO0_27/FC2_TXD_SCL_MISO/CTIMER3_MAT2/SCT0_OUT6/PDM0_DATA/SPIFI_IO(3), label: 'J13[12]/U27[7]/P0_27-SPIFI_IO3', identifier: SPIFI_IO3}
- {pin_num: '91', pin_signal: PIO0_28/FC0_SCK/CTIMER2_CAP3/SCT0_OUT7/TRACEDATA(3)/SPIFI_IO(2)/USB0_OVERCURRENTN, label: 'J13[10]/U27[3]/P0_28-SPIFI_IO2-USB0_OCURRn',
  identifier: SPIFI_IO2}
- {pin_num: '83', pin_signal: PIO0_25/FC0_TXD_SCL_MISO/SD_D(1)/CTIMER2_CAP1/SCT0_GPI1/SPIFI_IO(1), label: 'J13[4]/U27[2]/P0_25-SPIFI_IO1', identifier: SPIFI_IO1}
- {pin_num: '45', pin_signal: PIO2_12/LCD_LE/SD_VOLT(1)/USB0_IDVALUE/FC5_RXD_SDA_MOSI, label: 'U26A1[3]/P2_12-SPIFI_RSTn', identifier: SPIFI_RSTn}
- {pin_num: '11', pin_signal: PIO3_15/FC8_SCK/SD_WR_PRT, label: 'RP1[1]/U9[8]/P3_15-SD_WPn', identifier: SD_WPn}
- {pin_num: '39', pin_signal: PIO2_10/ENET_RX_ER/SD_CARD_DET_N, label: 'RP1[2]/U9[7]/P2_10-SD_CDn', identifier: SD_CDn}
- {pin_num: '32', pin_signal: PIO2_8/ENET_RXD2/SD_D(2)/CTIMER0_MAT0, label: 'RP1[3]/U9[6]/P2_8-SD_D2', identifier: SD_D2}
- {pin_num: '29', pin_signal: PIO2_7/ENET_COL/SD_D(1)/FREQME_GPIO_CLK_B/CTIMER0_CAP1, label: 'RP1[4]/U9[5]/P2_7-SD_D1', identifier: SD_D1}
- {pin_num: '17', pin_signal: PIO2_6/ENET_TX_CLK/SD_D(0)/FC1_RTS_SCL_SSEL1/CTIMER0_CAP0, label: 'RP1[5]/U9[4]/P2_6-SD_D0', identifier: SD_D0}
- {pin_num: '7', pin_signal: PIO2_3/ENET_TXD2/SD_CLK/FC1_RXD_SDA_MOSI/CTIMER2_MAT0, label: 'U9[3]/P2_3-SD_CLK', identifier: SD_CLK}
- {pin_num: '9', pin_signal: PIO2_4/ENET_TXD3/SD_CMD/FC1_TXD_SCL_MISO/CTIMER2_MAT1, label: 'RP1[6]/U9[2]/P2_4-SD_CMD', identifier: SD_CMD}
- {pin_num: '36', pin_signal: PIO2_9/ENET_RXD3/SD_D(3)/CTIMER0_MAT1, label: 'RP1[7]/U9[1]/P2_9-SD_D3', identifier: SD_D3}
- {pin_num: '12', pin_signal: PIO2_5/ENET_TX_ER/SD_POW_EN/FC1_CTS_SDA_SSEL0/CTIMER1_MAT2, label: 'Q3[1]/P2_5-SD_POW_EN', identifier: SD_POW_EN}
- {pin_num: '82', pin_signal: PIO3_25/CTIMER4_CAP2/FC4_SCK/EMC_A(14), label: 'U28[G8]/P3_25-EMC_A14', identifier: EMC_A14}
- {pin_num: '119', pin_signal: PIO1_25/FC2_TXD_SCL_MISO/SCT0_OUT2/UTICK_CAP0/EMC_A(13), label: 'U28[G7]/P1_25-EMC_A13', identifier: EMC_A13}
- {pin_num: '111', pin_signal: PIO1_24/FC2_RXD_SDA_MOSI/SCT0_OUT1/FC3_SSEL3/EMC_A(12), label: 'U28[G1]/P1_24-EMC_A12', identifier: EMC_A12}
- {pin_num: '97', pin_signal: PIO1_23/FC2_SCK/SCT0_OUT0/ENET_MDIO/FC3_SSEL2/EMC_A(11), label: 'U28[G2]/P1_23-EMC_A11', identifier: EMC_A11}
- {pin_num: '187', pin_signal: PIO1_16/ENET_MDC/FC6_TXD_SCL_MISO_WS/CTIMER1_MAT3/SD_CMD/EMC_A(10), label: 'U28[H9]/P1_16-EMC_A10', identifier: EMC_A10}
- {pin_num: '142', pin_signal: PIO1_27/FC2_RTS_SCL_SSEL1/SD_D(4)/CTIMER0_MAT3/CLKOUT/EMC_A(9), label: 'U28[G3]/P1_27-EMC_A9', identifier: EMC_A9}
- {pin_num: '131', pin_signal: PIO1_26/FC2_CTS_SDA_SSEL0/SCT0_OUT3/CTIMER0_CAP3/UTICK_CAP1/EMC_A(8), label: 'U28[H1]/P1_26-EMC_A8', identifier: EMC_A8}
- {pin_num: '72', pin_signal: PIO1_8/FC0_CTS_SDA_SSEL0/SD_CLK/SCT0_OUT1/FC4_SSEL2/EMC_A(7), label: 'U28[H2]/P1_8-EMC_A7', identifier: EMC_A7}
- {pin_num: '38', pin_signal: PIO1_7/FC0_RTS_SCL_SSEL1/SD_D(1)/CTIMER2_MAT2/SCT0_GPI4/EMC_A(6), label: 'U28[H3]/P1_7-EMC_A6', identifier: EMC_A6}
- {pin_num: '30', pin_signal: PIO1_6/FC0_TXD_SCL_MISO/SD_D(3)/CTIMER2_MAT1/SCT0_GPI3/EMC_A(5)}
- {pin_num: '5', pin_signal: PIO1_5/FC0_RXD_SDA_MOSI/SD_D(2)/CTIMER2_MAT0/SCT0_GPI0/EMC_A(4)}
- {pin_num: '158', pin_signal: PIO0_21/FC3_RTS_SCL_SSEL1/UTICK_CAP3/CTIMER3_MAT3/SCT0_GPI3/SCI0_SCLK/EMC_A(3)/FC7_SCK, label: 'U28[J7]/P0_21-EMC_A3', identifier: EMC_A3}
- {pin_num: '153', pin_signal: PIO0_20/FC3_CTS_SDA_SSEL0/CTIMER1_MAT1/CTIMER3_CAP3/SCT0_GPI2/SCI0_IO/EMC_A(2)/FC7_RXD_SDA_MOSI_DATA, label: 'U28[J8]/P0_20-EMC_A2',
  identifier: EMC_A2}
- {pin_num: '193', pin_signal: PIO0_19/FC4_RTS_SCL_SSEL1/UTICK_CAP0/CTIMER0_MAT2/SCT0_OUT2/EMC_A(1)/FC7_TXD_SCL_MISO_WS, label: 'U28[H8]/P0_19-EMC_A1', identifier: EMC_A1}
- {pin_num: '150', pin_signal: PIO0_18/FC4_CTS_SDA_SSEL0/SD_WR_PRT/CTIMER1_MAT0/SCT0_OUT1/SCI1_SCLK/EMC_A(0), label: 'U28[H7]/P0_18-EMC_A0', identifier: EMC_A0}
- {pin_num: '53', pin_signal: PIO0_15/FC6_CTS_SDA_SSEL0/UTICK_CAP2/CTIMER4_CAP0/SCT0_OUT2/EMC_WEN/ENET_TX_EN/ADC0_3, label: 'U28[F9]/P0_15-EMC_WEn', identifier: EMC_WEn}
- {pin_num: '78', pin_signal: PIO1_9/ENET_TXD0/FC1_SCK/CTIMER1_CAP0/SCT0_OUT2/FC4_CTS_SDA_SSEL0/EMC_CASN, label: 'U28[F7]/P1_9-EMC_CASn', identifier: EMC_CASn}
- {pin_num: '84', pin_signal: PIO1_10/ENET_TXD1/FC1_RXD_SDA_MOSI/CTIMER1_MAT0/SCT0_OUT3/EMC_RASN, label: 'U28[F8]/P1_10-EMC_RASn', identifier: EMC_RASn}
- {pin_num: '128', pin_signal: PIO1_12/ENET_RXD0/FC6_SCK/CTIMER1_MAT1/USB0_PORTPWRN/EMC_DYCSN(0), label: 'U28[G9]/P1_12-EMC_DYCSn0', identifier: EMC_DYCSn0}
- {pin_num: '195', pin_signal: PIO1_31/MCLK/CTIMER0_MAT2/SCT0_OUT6/FC8_CTS_SDA_SSEL0/EMC_D(15), label: 'U28[A2]/RP2[1]/P1_31-EMC_D15', identifier: EMC_D15}
- {pin_num: '182', pin_signal: PIO1_30/FC7_TXD_SCL_MISO_WS/SD_D(7)/SCT0_GPI7/USB1_OVERCURRENTN/USB1_UP_LED/EMC_D(14), label: 'U28[B1]/RP2[2]/P1_30-EMC_D14', identifier: EMC_D14}
- {pin_num: '165', pin_signal: PIO1_29/FC7_RXD_SDA_MOSI_DATA/SD_D(6)/SCT0_GPI6/USB1_PORTPWRN/USB1_FRAME/EMC_D(13), label: 'U28[B2]/RP2[3]/P1_29-EMC_D13', identifier: EMC_D13}
- {pin_num: '151', pin_signal: PIO1_28/FC7_SCK/SD_D(5)/CTIMER0_CAP2/EMC_D(12), label: 'U28[C1]/RP2[4]/P1_28-EMC_D12', identifier: EMC_D12}
- {pin_num: '3', pin_signal: PIO1_4/FC0_SCK/SD_D(0)/CTIMER2_MAT1/SCT0_OUT0/FREQME_GPIO_CLK_A/EMC_D(11), label: 'U28[C2]/RP4[1]/P1_4-EMC_D11', identifier: EMC_D11}
- {pin_num: '74', pin_signal: PIO1_21/FC7_CTS_SDA_SSEL0/CTIMER3_MAT2/FC4_RXD_SDA_MOSI/EMC_D(10), label: 'U28[D1]/RP4[2]/P1_21-EMC_D10', identifier: EMC_D10}
- {pin_num: '35', pin_signal: PIO1_20/FC7_RTS_SCL_SSEL1/CTIMER3_CAP2/FC4_TXD_SCL_MISO/EMC_D(9), label: 'U28[D2]/RP4[3]/P1_20-EMC_D9', identifier: EMC_D9}
- {pin_num: '33', pin_signal: PIO1_19/FC8_SCK/SCT0_OUT7/CTIMER3_MAT1/SCT0_GPI7/FC4_SCK/EMC_D(8), label: 'U28[E1]/RP4[4]/P1_19-EMC_D8', identifier: EMC_D8}
- {pin_num: '136', pin_signal: PIO0_9/FC3_SSEL2/SD_POW_EN/FC5_TXD_SCL_MISO/SCI1_IO/EMC_D(7), label: 'U28[E9]/RP5[1]/P0_9-EMC_D7', identifier: EMC_D7}
- {pin_num: '133', pin_signal: PIO0_8/FC3_SSEL3/SD_CMD/FC5_RXD_SDA_MOSI/SWO/PDM1_DATA/EMC_D(6), label: 'U28[D8]/RP5[2]/P0_8-EMC_D6', identifier: EMC_D6}
- {pin_num: '125', pin_signal: PIO0_7/FC3_RTS_SCL_SSEL1/SD_CLK/FC5_SCK/FC1_SCK/PDM1_CLK/EMC_D(5)/ENET_RX_CLK, label: 'U28[D9]/RP5[3]/P0_7-EMC_D5', identifier: EMC_D5}
- {pin_num: '191', pin_signal: PIO0_6/FC3_SCK/CTIMER3_CAP1/CTIMER4_MAT0/SCT0_GPI6/EMC_D(4)/ENET_RX_DV, label: 'U28[C8]/RP5[4]/SW2/P0_6-ISP2/P0_6-EMC_D4', identifier: SW2;EMC_D4}
- {pin_num: '160', pin_signal: PIO1_14/ENET_RX_DV/UTICK_CAP2/CTIMER1_MAT2/FC5_CTS_SDA_SSEL0/USB0_UP_LED/EMC_DQM(1), label: 'U28[F1]/P1_14-EMC_DQM1', identifier: EMC_DQM1}
- {pin_num: '139', pin_signal: PIO1_13/ENET_RXD1/FC6_RXD_SDA_MOSI_DATA/CTIMER1_CAP2/USB0_OVERCURRENTN/USB0_FRAME/EMC_DQM(0), label: 'U28[E8]/P1_13-EMC_DQM0', identifier: EMC_DQM0}
- {pin_num: '198', pin_signal: PIO1_11/ENET_TX_EN/FC1_TXD_SCL_MISO/CTIMER1_CAP1/USB0_VBUS/EMC_CLK(0), label: 'U28[F2]/P1_11-EMC_CLK0', identifier: EMC_CLK0}
- {pin_num: '176', pin_signal: PIO1_15/ENET_RX_CLK/UTICK_CAP3/CTIMER1_CAP3/FC5_RTS_SCL_SSEL1/FC4_RTS_SCL_SSEL1/EMC_CKE(0), label: 'U28[F3]/P1_15-EMC_CKE0', identifier: EMC_CKE0}
- {pin_num: '27', pin_signal: USB1_DP, label: 'J2[3]/U2[2]/U25[H3]/USB1_DP_TRGT', identifier: USB1_DP}
- {pin_num: '26', pin_signal: USB1_DM, label: 'J2[2]/U2[3]/U25[H2]/USB1_DM_TRGT', identifier: USB1_DM}
- {pin_num: '205', pin_signal: USB0_DM, label: 'J3[2]/U3[3]/USB0_DM_TRGT', identifier: USB0_DM}
- {pin_num: '204', pin_signal: USB0_DP, label: 'J3[3]/U3[2]/USB0_DP_TRGT', identifier: USB0_DP}
- {pin_num: '163', pin_signal: PIO0_22/FC6_TXD_SCL_MISO_WS/UTICK_CAP1/CTIMER3_CAP3/SCT0_OUT3/USB0_VBUS, label: 'U3[4]/J3[1]/P0_22-USB0_VBUS', identifier: USB0_VBUS}
- {pin_num: '23', pin_signal: USB1_VBUS, label: 'J2[1]/U2[4]/VBUS1_TARGET', identifier: USB1_VBUS}
- {pin_num: '22', pin_signal: USB1_ID, label: 'J2[4]/USB1_ID_TARGET', identifier: USB1_ID}
- {pin_num: '183', pin_signal: PIO4_11/ENET_RXD0/FC2_CTS_SDA_SSEL0/USB0_IDVALUE/SCT0_GPI4, label: 'U12[8]/JP12[1]/J3[4]/JP12[3]/P4_11-USB0_ID/P4_11-ENET_RXD0', identifier: USB0_ID;ENET_RXD0}
- {pin_num: '167', pin_signal: PIO0_29/FC0_RXD_SDA_MOSI/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA(2), label: 'U24[13]/P0_29-ISP_FC0_RXD', identifier: ISP_FC0_RXD}
- {pin_num: '200', pin_signal: PIO0_30/FC0_TXD_SCL_MISO/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA(1), label: 'U24[12]/P0_30-ISP_FC0_TXD', identifier: ISP_FC0_TXD}
- {pin_num: '52', pin_signal: PIO0_12/FC3_TXD_SCL_MISO/FREQME_GPIO_CLK_B/SCT0_GPI7/SWDIO/ADC0_2, label: 'P1[2]/U22[4]/D5[5]/IF_SWDIO', identifier: IF_SWDIO}
- {pin_num: '51', pin_signal: PIO0_11/FC6_RXD_SDA_MOSI_DATA/CTIMER2_MAT2/FREQME_GPIO_CLK_A/SWCLK/ADC0_1, label: 'U16[4]/SWDCLK_TRGT', identifier: SWDCLK_TRGT}
- {pin_num: '50', pin_signal: PIO0_10/FC6_SCK/CTIMER2_CAP2/CTIMER2_MAT0/FC1_TXD_SCL_MISO/SWO/ADC0_0, label: 'U16[12]/SWO_TRGT', identifier: SWO_TRGT}
- {pin_num: '99', pin_signal: PIO2_21/LCD_VD(3)/FC3_CTS_SDA_SSEL0/MCLK/CTIMER3_MAT3, label: 'J16[8]/P2_21-LCD_VD3', identifier: LCD_VD3}
- {pin_num: '113', pin_signal: PIO2_22/LCD_VD(4)/SCT0_OUT7/CTIMER2_CAP0, label: 'J16[9]/P2_22-LCD_VD4', identifier: LCD_VD4}
- {pin_num: '115', pin_signal: PIO2_23/LCD_VD(5)/SCT0_OUT8, label: 'J16[10]/P2_23-LCD_VD5', identifier: LCD_VD5}
- {pin_num: '118', pin_signal: PIO2_24/LCD_VD(6)/SCT0_OUT9, label: 'J16[11]/P2_24-LCD_VD6', identifier: LCD_VD6}
- {pin_num: '121', pin_signal: PIO2_25/LCD_VD(7)/USB0_VBUS, label: 'J16[12]/P2_25-LCD_VD7', identifier: LCD_VD7}
- {pin_num: '134', pin_signal: PIO2_28/LCD_VD(10)/FC7_CTS_SDA_SSEL0/CTIMER2_CAP2, label: 'J16[15]/P2_28-LCD_VD10', identifier: LCD_VD10}
- {pin_num: '137', pin_signal: PIO2_29/LCD_VD(11)/FC7_RTS_SCL_SSEL1/FC8_TXD_SCL_MISO/CTIMER2_CAP3/CLKOUT, label: 'J16[16]/P2_29-LCD_VD11', identifier: LCD_VD11}
- {pin_num: '143', pin_signal: PIO2_30/LCD_VD(12)/CTIMER2_MAT2, label: 'J16[17]/P2_30-LCD_VD12', identifier: LCD_VD12}
- {pin_num: '149', pin_signal: PIO2_31/LCD_VD(13), label: 'J16[18]/P2_31-LCD_VD13', identifier: LCD_VD13}
- {pin_num: '155', pin_signal: PIO3_0/LCD_VD(14)/PDM0_CLK/CTIMER1_MAT0, label: 'J16[19]/JS36[1]/P3_0-LCD_VD14', identifier: LCD_VD14}
- {pin_num: '159', pin_signal: PIO3_1/LCD_VD(15)/PDM0_DATA/CTIMER1_MAT1, label: 'J16[20]/JS33[1]/P3_1-LCD_VD15', identifier: LCD_VD15}
- {pin_num: '177', pin_signal: PIO3_5/LCD_VD(19)/FC8_RTS_SCL_SSEL1/CTIMER4_MAT1, label: 'J16[24]/P3_5-LCD_VD19', identifier: LCD_VD19}
- {pin_num: '180', pin_signal: PIO3_6/LCD_VD(20)/LCD_VD(0)/CTIMER4_MAT2, label: 'J16[25]/P3_6-LCD_VD20', identifier: LCD_VD20}
- {pin_num: '184', pin_signal: PIO3_7/LCD_VD(21)/LCD_VD(1)/CTIMER4_CAP2, label: 'J16[26]/P3_7-LCD_VD21', identifier: LCD_VD21}
- {pin_num: '186', pin_signal: PIO3_8/LCD_VD(22)/LCD_VD(2)/CTIMER4_CAP3, label: 'J16[27]/P3_8-LCD_VD22', identifier: LCD_VD22}
- {pin_num: '192', pin_signal: PIO3_9/LCD_VD(23)/LCD_VD(3)/CTIMER0_CAP2, label: 'J16[28]/P3_9-LCD_VD23', identifier: LCD_VD23}
- {pin_num: '70', pin_signal: PIO2_13/LCD_DCLK/SD_VOLT(2)/FC5_TXD_SCL_MISO, label: 'J16[30]/P2_13-LCD_DCLK', identifier: LCD_DCLK}
- {pin_num: '43', pin_signal: PIO2_11/LCD_PWR/SD_VOLT(0)/FC5_SCK, label: 'J16[31]/P2_11-LCD_PWR', identifier: LCD_PWR}
- {pin_num: '81', pin_signal: PIO2_16/LCD_LP/USB1_FRAME/USB1_PORTPWRN/CTIMER1_MAT3/FC8_SCK, label: 'J16[32]/P2_16-LCD_LP', identifier: LCD_LP}
- {pin_num: '77', pin_signal: PIO2_14/LCD_FP/USB0_FRAME/USB0_PORTPWRN/CTIMER0_MAT2/FC5_CTS_SDA_SSEL0, label: 'J16[33]/P2_14-LCD_FP', identifier: LCD_FP}
- {pin_num: '79', pin_signal: PIO2_15/LCD_AC/USB0_UP_LED/USB0_OVERCURRENTN/CTIMER0_MAT3/FC5_RTS_SCL_SSEL1, label: 'J16[34]/P2_15-LCD_AC_ENAB_M', identifier: LCD_AC_ENAB_M}
- {pin_num: '170', pin_signal: PIO4_8/ENET_TXD0/FC2_SCK/USB0_OVERCURRENTN/USB0_UP_LED/SCT0_GPI1, label: 'U12[17]/JP11[1]/P4_8-ENET_TXD0', identifier: ENET_TXD0}
- {pin_num: '146', pin_signal: PIO0_17/FC4_SSEL2/SD_CARD_DET_N/SCT0_GPI7/SCT0_OUT0/EMC_OEN/ENET_TXD1, label: 'U12[18]/P0_17-ENET_TXD1', identifier: ENET_TXD1}
- {pin_num: '190', pin_signal: PIO4_13/ENET_TX_EN/CTIMER4_MAT0/SCT0_GPI6, label: 'U12[16]/P4_13-ENET_TX_EN', identifier: ENET_TX_EN}
- {pin_num: '188', pin_signal: PIO4_12/ENET_RXD1/FC2_RTS_SCL_SSEL1/SCT0_GPI5, label: 'U12[7]/P4_12-ENET_RXD1', identifier: ENET_RXD1}
- {pin_num: '181', pin_signal: PIO4_10/ENET_RX_DV/FC2_TXD_SCL_MISO/USB1_OVERCURRENTN/USB1_UP_LED/SCT0_GPI3, label: 'U12[11]/P4_10-ENET_CRS_DV', identifier: ENET_CRS_DV}
- {pin_num: '203', pin_signal: PIO4_16/ENET_MDIO/CTIMER4_MAT3/FC9_TXD_SCL_MISO, label: 'U12[12]/P4_16-ENET_MDIO', identifier: ENET_MDIO}
- {pin_num: '197', pin_signal: PIO4_15/ENET_MDC/CTIMER4_MAT2/FC9_RXD_SDA_MOSI, label: 'U12[13]/P4_15-ENET_MDC', identifier: ENET_MDC}
- {pin_num: '124', pin_signal: PIO2_26/LCD_VD(8)/FC3_SCK/CTIMER2_CAP1, label: 'U12[15]/P2_26-ENET_PHY_RSTn', identifier: ENET_PHY_RSTn}
- {pin_num: '194', pin_signal: PIO4_14/ENET_RX_CLK/CTIMER4_MAT1/FC9_SCK/SCT0_GPI7, label: 'JS18[2]/P4_14-ENET_RX_CLK', identifier: ENET_RX_CLK}
- {pin_num: '117', pin_signal: PIO1_2/CAN0_TD/CTIMER0_MAT3/SCT0_GPI6/PDM1_CLK/USB1_PORTPWRN, label: 'J13[18]/JS25[3]/DMIC1[4]/P1_2-PDM1_CLK', identifier: PDM1_CLK}
- {pin_num: '120', pin_signal: PIO1_3/CAN0_RD/SCT0_OUT4/PDM1_DATA/USB0_PORTPWRN, label: 'JS26[3]/DMIC1[1]/P1_3-PDM1_DATA', identifier: PDM1_DATA}
- {pin_num: '132', pin_signal: PIO4_1/FC6_SCK/SCT0_GPI2/EMC_CSN(2), label: 'U10[29]/J9[14]/P4_1-FC6_I2S_TX_SCK', identifier: FC6_I2S_TX_SCK}
- {pin_num: '140', pin_signal: PIO4_3/FC6_TXD_SCL_MISO_WS/CTIMER0_CAP3/SCT0_GPI4/EMC_DYCSN(2), label: 'U10[30]/J9[12]/P4_3-FC6_I2S_TX_WS', identifier: FC6_I2S_TX_WS}
- {pin_num: '138', pin_signal: PIO4_2/FC6_RXD_SDA_MOSI_DATA/SCT0_GPI3/EMC_CSN(3), label: 'U10[32]/J9[10]/P4_2-FC6_I2S_TX_DATA', identifier: FC6_I2S_TX_DATA}
- {pin_num: '93', pin_signal: PIO2_19/LCD_VD(1)/FC3_TXD_SCL_MISO/FC7_RXD_SDA_MOSI_DATA/CTIMER3_MAT1, label: 'U10[31]/J9[20]/P2_19-FC7_I2S_RX_DAT', identifier: FC7_I2S_RX_DAT}
- {pin_num: '90', pin_signal: PIO2_18/LCD_VD(0)/FC3_RXD_SDA_MOSI/FC7_SCK/CTIMER3_MAT0, label: 'U10[29]/J9[16]/P2_18-FC7_I2S_RX_SCK', identifier: FC7_I2S_RX_SCK}
- {pin_num: '95', pin_signal: PIO2_20/LCD_VD(2)/FC3_RTS_SCL_SSEL1/FC7_TXD_SCL_MISO_WS/CTIMER3_MAT2/CTIMER4_CAP0, label: 'U10[30]/J9[18]/P2_20-FC7_I2S_RX_WS', identifier: FC7_I2S_RX_WS}
- {pin_num: '208', pin_signal: PIO3_11/MCLK/FC0_SCK/FC1_SCK/TRACEDATA(3), label: 'J11[8]/J12[7]/P3_11-MCLK-PMOD2_GPIO', identifier: MCLK}
- {pin_num: '15', pin_signal: PIO1_18/FC8_TXD_SCL_MISO/SCT0_OUT5/CAN1_RD/EMC_BLSN(1), label: 'J9[2]/P1_18-CAN1_RD'}
- {pin_num: '54', pin_signal: PIO0_16/FC4_TXD_SCL_MISO/CLKOUT/CTIMER1_CAP0/EMC_CSN(0)/ENET_TXD0/ADC0_4, label: 'J12[2]/P0_16-ADC0IN4'}
- {pin_num: '55', pin_signal: PIO0_31/FC0_CTS_SDA_SSEL0/SD_D(2)/CTIMER0_MAT1/SCT0_OUT3/TRACEDATA(0)/ADC0_5, label: 'J12[4]/P0_31-ADC0IN5'}
- {pin_num: '56', pin_signal: PIO1_0/FC0_RTS_SCL_SSEL1/SD_D(3)/CTIMER0_CAP2/SCT0_GPI4/TRACECLK/ADC0_6, label: 'J12[6]/P0_31-ADC0IN5'}
- {pin_num: '98', pin_signal: PIO1_17/ENET_MDIO/FC8_RXD_SDA_MOSI/SCT0_OUT4/CAN1_TD/EMC_BLSN(0), label: 'J9[4]/P1_17-CAN1_TD'}
- {pin_num: '89', pin_signal: PIO1_22/FC8_RTS_SCL_SSEL1/SD_CMD/CTIMER2_MAT3/SCT0_GPI5/FC4_SSEL3/EMC_CKE(1), label: 'J13[1]/P1_22-CT2MAT3'}
- {pin_num: '57', pin_signal: PIO2_0/FC0_RXD_SDA_MOSI/CTIMER1_CAP0/ADC0_7, label: 'J12[8]/P2_0-ADC0IN7-PMOD2_INTR'}
- {pin_num: '58', pin_signal: PIO2_1/FC0_TXD_SCL_MISO/CTIMER1_MAT0/ADC0_8, label: 'J9[17]/P2_1-CT1MAT0'}
- {pin_num: '86', pin_signal: PIO2_17/LCD_CLKIN/USB1_UP_LED/USB1_OVERCURRENTN/CTIMER1_CAP1/FC8_RXD_SDA_MOSI, label: 'J13[20]/P2_17-CT1CAP1-FC8_RXD'}
- {pin_num: '130', pin_signal: PIO2_27/LCD_VD(9)/FC9_SCK/FC3_SSEL2, label: 'J17[2]/P2_27-CT_RSTn'}
- {pin_num: '164', pin_signal: PIO3_2/LCD_VD(16)/FC9_RXD_SDA_MOSI/CTIMER1_MAT2, label: 'J13[11]/P3_2-FC9_MOSI-CT1MAT2'}
- {pin_num: '199', pin_signal: PIO3_10/SCT0_OUT3/CTIMER3_MAT0/EMC_DYCSN(1)/TRACEDATA(0), label: 'J13[7]/P3_10-CT3MAT0'}
- {pin_num: '37', pin_signal: PIO3_12/SCT0_OUT8/CTIMER3_CAP0/CLKOUT/EMC_CLK(1)/TRACECLK, label: 'J12[9]/P3_12-CLKOUT'}
- {pin_num: '19', pin_signal: PIO3_16/FC8_RXD_SDA_MOSI/SD_D(4), label: 'J12[3]/P3_16-GPIO_SPI_CS2'}
- {pin_num: '31', pin_signal: PIO3_17/FC8_TXD_SCL_MISO/SD_D(5), label: 'JS25[1]/P3_17-FC8_TXD'}
- {pin_num: '68', pin_signal: PIO3_18/FC8_CTS_SDA_SSEL0/SD_D(6)/CTIMER4_MAT0/CAN0_TD/SCT0_OUT5, label: 'J10[4]/P3_17-FC8_TXD'}
- {pin_num: '44', pin_signal: PIO3_19/FC8_RTS_SCL_SSEL1/SD_D(7)/CTIMER4_MAT1/CAN0_RD/SCT0_OUT6, label: 'J10[2]/P3_19-CAN0_RD'}
- {pin_num: '46', pin_signal: PIO3_20/FC9_SCK/SD_CARD_INT_N/CLKOUT/SCT0_OUT7, label: 'J9[9]/P3_20-FC9_SCK'}
- {pin_num: '61', pin_signal: PIO3_21/FC9_RXD_SDA_MOSI/SD_BACKEND_PWR/CTIMER4_MAT3/UTICK_CAP2/ADC0_9, label: 'J9[13]/P3_21-FC9_MOSI'}
- {pin_num: '62', pin_signal: PIO3_22/FC9_TXD_SCL_MISO/ADC0_10, label: 'J9[11]/P3_21-FC9_MISO'}
- {pin_num: '88', pin_signal: PIO3_26/SCT0_OUT0/FC4_RXD_SDA_MOSI/EMC_A(15), label: 'J13[15]/P3_26-FC4_RXD'}
- {pin_num: '96', pin_signal: PIO3_27/SCT0_OUT1/FC4_TXD_SCL_MISO/EMC_A(16), label: 'J13[13]/P3_26-FC4_TXD'}
- {pin_num: '100', pin_signal: PIO3_28/SCT0_OUT2/FC4_CTS_SDA_SSEL0/EMC_A(17), label: 'JS26[1]/P3_28-FC4_CTS_SDAX'}
- {pin_num: '112', pin_signal: PIO3_29/SCT0_OUT3/FC4_RTS_SCL_SSEL1/EMC_A(18), label: 'J13[14]/P3_29-FC4_RTS_SCLX'}
- {pin_num: '116', pin_signal: PIO3_30/FC9_CTS_SDA_SSEL0/SCT0_OUT4/FC4_SSEL2/EMC_A(19), label: 'J9[15]/P3_30-FC9_SSELn0'}
- {pin_num: '123', pin_signal: PIO3_31/FC9_RTS_SCL_SSEL1/SCT0_OUT5/CTIMER4_MAT2/SCT0_GPI0/EMC_A(20), label: 'U14[4]/P3_31-SCT0_OUT5_CT4MAT2'}
- {pin_num: '127', pin_signal: PIO4_0/FC6_CTS_SDA_SSEL0/CTIMER4_CAP1/SCT0_GPI1/EMC_CSN(1), label: 'J17[3]/P4_0-CT_INTR'}
- {pin_num: '147', pin_signal: PIO4_4/FC4_SSEL3/FC0_RTS_SCL_SSEL1/SCT0_GPI5/EMC_DYCSN(3), label: 'J13[19]/P4_4'}
- {pin_num: '154', pin_signal: PIO4_5/FC9_CTS_SDA_SSEL0/FC0_CTS_SDA_SSEL0/CTIMER4_MAT3/SCT0_GPI6/EMC_CKE(2), label: 'J13[9]/P4_5-CT4MAT3'}
- {pin_num: '161', pin_signal: PIO4_6/FC9_RTS_SCL_SSEL1/SCT0_GPI7/EMC_CKE(3), label: 'J12[1]/P4_6-FC9_SSELn1'}
- {pin_num: '166', pin_signal: PIO4_7/CTIMER4_CAP3/USB0_PORTPWRN/USB0_FRAME/SCT0_GPI0, label: P4_7}
- {pin_num: '173', pin_signal: PIO4_9/ENET_TXD1/FC2_RXD_SDA_MOSI/USB1_PORTPWRN/USB1_FRAME/SCT0_GPI2, label: 'U29[2]/P4_9-USB1_PORTPWRn'}
- {pin_num: '101', pin_signal: RESET, label: 'J15[1]/nRESET_TRGT'}
- {pin_num: '105', pin_signal: RTCXIN, label: Y4}
- {pin_num: '106', pin_signal: RTCXOUT, label: Y4}
- {pin_num: '20', pin_signal: USB1_AVSSC, label: GND}
- {pin_num: '28', pin_signal: USB1_AVSSTX3V3, label: GND}
- {pin_num: '21', pin_signal: USB1_REXT, label: GND}
- {pin_num: '1', pin_signal: VDD1, label: VDD_TARGET_IC}
- {pin_num: '64', pin_signal: VDDA, label: VDD_TARGET}
- {pin_num: '63', pin_signal: VREFP, label: 'JS23[1]'}
- {pin_num: '59', pin_signal: VREFN, label: 'JS22[2]'}
- {pin_num: '2', pin_signal: VSS2, label: GND}
- {pin_num: '60', pin_signal: VSSA, label: GND}
- {pin_num: '41', pin_signal: XTAL1, label: Y2}
- {pin_num: '40', pin_signal: XTAL2, label: Y2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONsPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitBUTTONsPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitLEDsPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPMod_SPI_I2C_BRIDGEPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '144', peripheral: FLEXCOMM1, signal: RTS_SCL_SSEL1, pin_signal: PIO0_14/FC1_RTS_SCL_SSEL1/UTICK_CAP1/CTIMER0_CAP1/SCT0_GPI1/ENET_RXD1, i2c_slew: i2c}
  - {pin_num: '141', peripheral: FLEXCOMM1, signal: CTS_SDA_SSEL0, pin_signal: PIO0_13/FC1_CTS_SDA_SSEL0/UTICK_CAP0/CTIMER0_CAP0/SCT0_GPI0/ENET_RXD0, i2c_slew: i2c}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPMod_SPI_I2C_BRIDGEPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitPMod_SPI_I2C_BRIDGEPins(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][13] = ((IOCON->PIO[0][13] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_I2CSLEW_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT013 (pin 141) is configured as FC1_CTS_SDA_SSEL0. */
                         | IOCON_PIO_FUNC(PIO013_FUNC_ALT1)

                         /* Controls slew rate of I2C pad.
                          * : I2C mode. */
                         | IOCON_PIO_I2CSLEW(PIO013_I2CSLEW_I2C_MODE)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO013_DIGIMODE_DIGITAL));

    IOCON->PIO[0][14] = ((IOCON->PIO[0][14] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_I2CSLEW_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT014 (pin 144) is configured as FC1_RTS_SCL_SSEL1. */
                         | IOCON_PIO_FUNC(PIO014_FUNC_ALT1)

                         /* Controls slew rate of I2C pad.
                          * : I2C mode. */
                         | IOCON_PIO_I2CSLEW(PIO014_I2CSLEW_I2C_MODE)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO014_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitACCELPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitACCELPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitACCELPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitQSPI_FLASHPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitQSPI_FLASHPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitQSPI_FLASHPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSDHCPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSDHCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitSDHCPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSDRAMPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSDRAMPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitSDRAMPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUSBPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUSBPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitUSBPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '30', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO1_6/FC0_TXD_SCL_MISO/SD_D(3)/CTIMER2_MAT1/SCT0_GPI3/EMC_A(5), mode: inactive}
  - {pin_num: '5', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO1_5/FC0_RXD_SDA_MOSI/SD_D(2)/CTIMER2_MAT0/SCT0_GPI0/EMC_A(4), mode: inactive}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitDEBUG_UARTPins(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[1][5] = ((IOCON->PIO[1][5] &
                         /* Mask bits to zero which are setting */
                         (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Selects pin function.
                         * : PORT15 (pin 5) is configured as FC0_RXD_SDA_MOSI. */
                        | IOCON_PIO_FUNC(PIO15_FUNC_ALT1)

                        /* Selects function mode (on-chip pull-up/pull-down resistor control).
                         * : Inactive.
                         * Inactive (no pull-down/pull-up resistor enabled). */
                        | IOCON_PIO_MODE(PIO15_MODE_INACTIVE)

                        /* Select Analog/Digital mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO15_DIGIMODE_DIGITAL));

    IOCON->PIO[1][6] = ((IOCON->PIO[1][6] &
                         /* Mask bits to zero which are setting */
                         (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Selects pin function.
                         * : PORT16 (pin 30) is configured as FC0_TXD_SCL_MISO. */
                        | IOCON_PIO_FUNC(PIO16_FUNC_ALT1)

                        /* Selects function mode (on-chip pull-up/pull-down resistor control).
                         * : Inactive.
                         * Inactive (no pull-down/pull-up resistor enabled). */
                        | IOCON_PIO_MODE(PIO16_MODE_INACTIVE)

                        /* Select Analog/Digital mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO16_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSWD_DEBUGPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSWD_DEBUGPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitSWD_DEBUGPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLCDPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLCDPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitLCDPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitENETPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitENETPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitENETPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDMICPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDMICPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitDMICPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2SPins:
- options: {prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2SPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitI2SPins(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
